// Code generated by goctl. DO NOT EDIT.
// Source: data.proto

package server

import (
	"context"

	"travel/app/data/cmd/rpc/internal/logic"
	"travel/app/data/cmd/rpc/internal/svc"
	"travel/app/data/cmd/rpc/pb/pb"
)

type DataServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDataServer
}

func NewDataServer(svcCtx *svc.ServiceContext) *DataServer {
	return &DataServer{
		svcCtx: svcCtx,
	}
}

func (s *DataServer) ContentSimilar(ctx context.Context, in *pb.ContentSimilarReq) (*pb.ContentSimilarResp, error) {
	l := logic.NewContentSimilarLogic(ctx, s.svcCtx)
	return l.ContentSimilar(in)
}

func (s *DataServer) UserLikeContent(ctx context.Context, in *pb.UserLikeContentReq) (*pb.UserLikeContentResp, error) {
	l := logic.NewUserLikeContentLogic(ctx, s.svcCtx)
	return l.UserLikeContent(in)
}

func (s *DataServer) ContentTagCreate(ctx context.Context, in *pb.ContentTagCreateReq) (*pb.ContentTagCreateResp, error) {
	l := logic.NewContentTagCreateLogic(ctx, s.svcCtx)
	return l.ContentTagCreate(in)
}
