// Code generated by goctl. DO NOT EDIT.
package types

type ConversationCreateReq struct {
	Content     string `json:"content"`
	IsGenerated bool   `json:"isGenerated"`
}

type ConversationGenerateReq struct {
	Content     string `json:"content"`
	IsGenerated bool   `json:"isGenerated"`
}

type ConversationGenerateResp struct {
	Content string `json:"content"`
}

type ConversationListResp struct {
	List []ConversationView `json:"list"`
}

type ConversationView struct {
	Id          int64  `json:"id"`
	Content     string `json:"content"`
	IsGenerated bool   `json:"isGenerated"`
}

type StrategyCreateReq struct {
	Destination string `json:"destination"`
	Duration    string `json:"duration"`
	Budget      string `json:"budget"`
	TripGroup   string `json:"tripGroup"`
	TripMood    string `json:"tripMood"`
	Strategy    string `json:"strategy"`
}

type StrategyDeleteReq struct {
	Id int64 `json:"id"`
}

type StrategyDetailReq struct {
	Id int64 `json:"id"`
}

type StrategyDetailResp struct {
	Strategy StrategyView `json:"strategy"`
}

type StrategyGenerateReq struct {
	Destination string `json:"destination"`
	Duration    string `json:"duration"`
	Budget      string `json:"budget"`
	TripGroup   string `json:"tripGroup"`
	TripMood    string `json:"tripMood"`
}

type StrategyGenerateResp struct {
	Strategy string `json:"strategy"`
}

type StrategyListResp struct {
	List []StrategyView `json:"list"`
}

type StrategyView struct {
	Id          int64  `json:"id"`
	Destination string `json:"destination"`
	Duration    string `json:"duration"`
	Budget      string `json:"budget"`
	TripGroup   string `json:"tripGroup"`
	TripMood    string `json:"tripMood"`
	Strategy    string `json:"strategy"`
	CreateTime  string `json:"createTime"`
}
