// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"travel/app/data/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/data/behavior/create",
				Handler: BehaviorCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/data/content/create",
				Handler: ContentTagCreateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
