// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"travel/app/data/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/data/behavior/create",
				Handler: BehaviorCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/data/file/upload",
				Handler: FileUploadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithTimeout(30000*time.Millisecond),
		rest.WithMaxBytes(104857600),
	)
}
