// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"travel/app/user/cmd/api/internal/handler/auth"
	"travel/app/user/cmd/api/internal/handler/follow"

	"travel/app/user/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/follow",
				Handler: follow.FollowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/follow/list",
				Handler: follow.FollowListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/userinfo",
				Handler: UserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
