// Code generated by goctl. DO NOT EDIT.
package types

type BehaviorCreateReq struct {
	BehaviorItemType int   `json:"behavoirItemType"`
	BehaviorItemId   int64 `json:"behaviorItemId"`
	BehaviorType     int   `json:"behaviorType"`
}

type ContentTagCreateReq struct {
	Name     []string `json:"name"`
	ItemType int      `json:"itemType"`
	ItemId   int64    `json:"itemId"`
}
