// Code generated by goctl. DO NOT EDIT.
package types

type BehaviorCreateReq struct {
	BehaviorItemType int   `json:"behavoirItemType"`
	BehaviorItemId   int64 `json:"behaviorItemId"`
	BehaviorType     int   `json:"behaviorType"`
}

type ContentTagCreateReq struct {
	Name     []string `json:"name"`
	ItemType int      `json:"itemType"`
	ItemId   int64    `json:"itemId"`
}

type UploadReq struct {
	FileName string `json:"fileName"`
	File     []byte `json:"file"`
}

type UploadResp struct {
	FileUrl string `json:"fileUrl"`
}
