// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResp struct {
	Id      int64  `json:"id"`
	Account string `json:"account"`
	Email   string `json:"email"`
}

type UserInfoReq struct {
	Id int64 `json:"id"`
}

type UserInfoResp struct {
	Id         int64  `json:"id"`
	Account    string `json:"account"`
	Email      string `json:"email"`
	Avatar     string `json:"avatar"'`
	Signature  string `json:"signature"`
	IsFollowed bool   `json:"isFollowed"`
	CreateTime string `json:"createTime" format:"date-time"`
	UpdateTime string `json:"updateTime" format:"date-time"`
}

type FollowListReq struct {
	Id       int64 `json:"id"`
	PageNum  int64 `json:"pageNum"`
	PageSize int64 `json:"pageSize"`
}

type FollowListView struct {
	UserInfo []UserInfoResp `json:"userInfo"`
	Total    int64          `json:"total"`
}

type FollowReq struct {
	Id   int64 `json:"id"`
	Type bool  `json:"type"`
}
