// Code generated by goctl. DO NOT EDIT.
package types

type CopyrightView struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId"`
	ItemType   int    `json:"itemType"`
	ItemId     int64  `json:"itemId"`
	Metadata   string `json:"metadata"`
	TradeHash  string `json:"tradeHash"`
	Address    string `json:"address"`
	Status     int    `json:"status"`
	CreateTime string `json:"createTime"`
	Title      string `json:"title"`
	CoverUrl   string `json:"coverUrl"`
	Content    string `json:"content"`
}

type RecordCreateReq struct {
	WorkId int64 `json:"workId"`
	UserId int64 `json:"userId"`
}

type RecordListReq struct {
	WorkId int64 `json:"workId"`
}

type RecordListResp struct {
	List []RecordView `json:"list"`
}

type RecordView struct {
	Id          int64        `json:"id"`
	OldUserId   int64        `json:"oldUserId"`
	OldUserInfo UserInfoView `json:"oldUserInfo"`
	NewUserId   int64        `json:"newUserId"`
	NewUserInfo UserInfoView `json:"newUserInfo"`
	Price       string       `json:"price"`
	CreateTime  string       `json:"createTime"`
}

type UserInfoView struct {
	UserId     int64  `json:"userId"`
	Account    string `json:"account"`
	Email      string `json:"email"`
	Avatar     string `json:"avatar"`
	IsFollowed bool   `json:"isFollowed"`
}

type UserWorkListReq struct {
	UserId   int64 `json:"userId"`
	PageNum  int   `json:"pageNum"`
	PageSize int   `json:"pageSize"`
}

type UserWorkListResp struct {
	List  []WorkView `json:"list"`
	Total int        `json:"total"`
}

type WorkCreateReq struct {
	CopyrightId int64  `json:"copyrightId"`
	Price       string `json:"price"`
}

type WorkDetailReq struct {
	Id int64 `json:"id"`
}

type WorkDetailResp struct {
	Work      WorkView      `json:"work"`
	UserInfo  UserInfoView  `json:"userInfo"`
	Copyright CopyrightView `json:"copyright"`
}

type WorkListReq struct {
	PageNum  int `json:"pageNum"`
	PageSize int `json:"pageSize"`
}

type WorkListResp struct {
	List  []WorkView `json:"list"`
	Total int        `json:"total"`
}

type WorkUpdateReq struct {
	Id   int64 `json:"id"`
	Type int   `json:"type"`
}

type WorkView struct {
	Id          int64  `json:"id"`
	UserId      int64  `json:"userId"`
	CopyrightId int64  `json:"copyrightId"`
	Price       string `json:"price"`
	Status      int    `json:"status"`
	CreateTime  string `json:"createTime"`
	Account     string `json:"account"`
	Avatar      string `json:"avatar"`
	ItemType    int    `json:"itemType"`
	Title       string `json:"title"`
	CoverUrl    string `json:"coverUrl"`
	Content     string `json:"content"`
}
