// Code generated by goctl. DO NOT EDIT.
package types

type CopyrightView struct {
	Id             int64  `json:"id"`
	UserId         int64  `json:"userId"`
	ItemType       int    `json:"itemType"`
	ItemId         int64  `json:"itemId"`
	Metadata       string `json:"metadata"`
	IpfsHash       string `json:"ipfsHash"`
	TokenId        int64  `json:"tokenId"`
	AccountAddress string `json:"accountAddress"`
	Status         int    `json:"status"`
	CreateTime     string `json:"createTime"`
	Title          string `json:"title"`
	CoverUrl       string `json:"coverUrl"`
	Content        string `json:"content"`
	Description    string `json:"description"`
}

type RecordCreateReq struct {
	WorkId int64 `json:"workId"`
	UserId int64 `json:"userId"`
}

type RecordListReq struct {
	WorkId int64 `json:"workId"`
}

type RecordListResp struct {
	List []RecordView `json:"list"`
}

type RecordView struct {
	Id                int64        `json:"id"`
	WorkId            int64        `json:"workId"`
	CopyrightId       int64        `json:"copyrightId"`
	OldUserId         int64        `json:"oldUserId"`
	OldAccountAddress string       `json:"oldAccountAddress"`
	NewAccountAddress string       `json:"newAccountAddress"`
	OldUserInfo       UserInfoView `json:"oldUserInfo"`
	NewUserId         int64        `json:"newUserId"`
	NewUserInfo       UserInfoView `json:"newUserInfo"`
	Price             string       `json:"price"`
	CreateTime        string       `json:"createTime"`
}

type UserInfoView struct {
	UserId     int64  `json:"userId"`
	Account    string `json:"account"`
	Email      string `json:"email"`
	Avatar     string `json:"avatar"`
	IsFollowed bool   `json:"isFollowed"`
}

type UserWorkListReq struct {
	UserId   int64 `json:"userId"`
	PageNum  int   `json:"pageNum"`
	PageSize int   `json:"pageSize"`
}

type UserWorkListResp struct {
	List  []WorkView `json:"list"`
	Total int        `json:"total"`
}

type WorkCreateReq struct {
	CopyrightId int64  `json:"copyrightId"`
	Price       string `json:"price"`
}

type WorkDetailReq struct {
	Id int64 `json:"id"`
}

type WorkDetailResp struct {
	Work      WorkView      `json:"work"`
	UserInfo  UserInfoView  `json:"userInfo"`
	Copyright CopyrightView `json:"copyright"`
}

type WorkListReq struct {
	PageNum  int `json:"pageNum"`
	PageSize int `json:"pageSize"`
}

type WorkListResp struct {
	List  []WorkView `json:"list"`
	Total int        `json:"total"`
}

type WorkUpdateReq struct {
	Id                int64  `json:"id"`
	Type              int    `json:"type"`
	OldAccountAddress string `json:"oldAccountAddress"`
	AccountAddress    string `json:"accountAddress"`
}

type WorkView struct {
	Id             int64  `json:"id"`
	UserId         int64  `json:"userId"`
	CopyrightId    int64  `json:"copyrightId"`
	Price          string `json:"price"`
	Status         int    `json:"status"`
	CreateTime     string `json:"createTime"`
	AccountAddress string `json:"accountAddress"`
	Account        string `json:"account"`
	Avatar         string `json:"avatar"`
	ItemType       int    `json:"itemType"`
	Title          string `json:"title"`
	CoverUrl       string `json:"coverUrl"`
	Content        string `json:"content"`
	Description    string `json:"description"`
}
